// This file generated by ngrestcg
// For more information, please visit: https://github.com/loentar/ngrest

#ifndef $($serviceNs.!mangledot.!toupper)_H
#define $($serviceNs.!mangledot.!toupper)_H

#include <ngrest/common/Service.h>

##ifneq($($ns),)
namespace $($ns.!replace/./ {\nnamespace /) {

##endif
//! Dummy description for the service
/*! Some detailed description of the service */
// '*location' comment sets resource path for this service
// *location: $($service.!tolower)
class $($service): public ngrest::Service
{
public:
    // Here is an example of service operation
    //! Dummy description for the operation
    /*! Some detailed description of the operation */
    // To invoke this operation from browser open: http://localhost:9098/$($service.!tolower)/World!
    //
    // '*location' metacomment sets path to operation relative to service operation.
    // Default value is operation name.
    // This will bind "echo" method to resource path: http://host:port/$($service.!tolower)/{text}
    // *location: /{text}
    //
    // '*method' metacomment sets HTTP method for the operation. GET is default method.
    // *method: GET
    //
    std::string echo(const std::string& text)
    {
        return "Hi, " + text;
    }
};

##ifneq($($ns),)
}
$($ns.!replacenotof/.//.!replace/./}\n/)\
##endif

#endif // $($serviceNs.!mangledot.!toupper)_H



