sudo: required
dist: trusty
language: cpp
env:
  - WITH_EXAMPLES=1 WITH_TESTS=1
compiler:
  - gcc
before_script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=DEBUG ..
script:
  - make
  - cd deploy/tests
  - ./ngrestjsontest
  - ./test_server_client
