// This file generated by ngrestcg
// For more information, please visit: https://github.com/loentar/ngrest

#include "$($service).h"

##ifneq($($ns),)
namespace $($ns.!replace/./ {\nnamespace /) {

##endif
std::string $($service)::echo(const std::string& text)
{
    return "Hi, " + text;
}

##ifneq($($ns),)
}
$($ns.!replacenotof/.//.!replace/./}\n/)\
##endif
